//file:noinspection GroovyAssignabilityCheck
//file:noinspection GrUnresolvedAccess
ext {
    moduleName = 'java-immutable-json-model'
}

apply from: "${rootDir}/${rootProject.configurationPath}/shared-gradle-files/standard-module.gradle"

dependencies {
    implementation project(":model")

    implementation 'org.apache.commons:commons-lang3:' + rootProject.dependencyVersions.apacheCommonsCommonsLang3Version
}