//file:noinspection GroovyAssignabilityCheck
//file:noinspection GrUnresolvedAccess
//file:noinspection DependencyNotationArgument
ext {
    moduleName = 'java-immutable-model-sample'
}

apply from: "${rootDir}/${rootProject.configurationPath}/shared-gradle-files/standard-module.gradle"


dependencies {
    implementation project(':model')

    implementation 'org.apache.commons:commons-lang3:' + rootProject.dependencyVersions.apacheCommonsCommonsLang3Version
}